development:
  enable_star: true
  min_infix_len: 3
  charset_table: 0..9, A..Z->a..z, _, a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F

production:
  enable_star: true
  min_infix_len: 3
  charset_table: 0..9, A..Z->a..z, _, a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F

  pid_file: /home/hosting_vivanov2/projects/pricer/shared/pids/searchd.pid
  searchd_file_path: /home/hosting_vivanov2/projects/pricer/shared/sphinx/production
  log:  /home/hosting_vivanov2/projects/pricer/shared/log/searchd.log
  query_log:  /home/hosting_vivanov2/projects/pricer/shared/log/searchd.query.log
  port: 33444

